services:
  meta-swap-api:
    image: superioragents/meta-swap-api
    build:
      context: meta-swap-api
      dockerfile: Dockerfile
    ports:
      - "${TRADE_API_PORT:-9009}:${TRADE_API_PORT:-9009}"

    env_file:
      - meta-swap-api/.env

    restart: unless-stopped