version: '3.8'

services:
  agent-executor:
    image: superioragents/agent-executor:latest

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    volumes:
      - ./agent/db/:/app/db
      - ./agent/code:/app/code
      - ./agent/src:/app/src
      - ./agent/scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
      - SQLITE_PATH=/app/db/superior-agents.db
    command: sleep infinity
    networks:
      - app-network

  meta-swap-api:
    build:
      context: ./meta-swap-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    command: sleep infinity
    
networks:
  app-network:
    driver: bridge